'use client';
import {useEffect, useState} from 'react';

const zones=[['Wuse','z1','Markets • Food • Offices'],['Maitama','z2','Luxury • Hotels • Estates'],['Jabi','z3','Lake • Mall • Entertainment'],['Garki','z4','Business • Hospitals'],['Gwarinpa','z5','Homes • Shops • Food'],['Asokoro','z6','Estates • Government']];
const people=['Ada_Wuse','TundeJabi','MusaGarki'];
export default function Home(){
 const [play,setPlay]=useState(false); const [name,setName]=useState(''); const [avatar,setAvatar]=useState('🧑🏾'); const [started,setStarted]=useState(false); const [zone,setZone]=useState('Wuse'); const [citizenId,setCitizenId]=useState<string|null>(null); const [wallet,setWallet]=useState(25000); const [job,setJob]=useState<string|null>(null); const [online,setOnline]=useState(people);
 useEffect(()=>{fetch('/api/citizens').then(r=>r.json()).then(x=>{if(x.citizens?.length)setOnline(x.citizens.map((c:any)=>c.username));}).catch(()=>{});},[]);
 const enterCity=async()=>{if(!name.trim())return; try { const r=await fetch('/api/citizens',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:name,avatar})}); const x=await r.json(); if(!r.ok) return alert(x.error||'Could not create citizen'); setCitizenId(x.citizen?.id||null); setWallet(x.citizen?.wallet||25000); setJob(x.citizen?.job||null); setStarted(true); setOnline(p=>Array.from(new Set([name,...p]))); } catch { setStarted(true); }};
 const findJob=async()=>{ if(!citizenId){alert('Enter the city first.');return;} const r=await fetch('/api/jobs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({citizenId,jobId:'tech'})}); const x=await r.json(); if(r.ok)setJob(x.job.title); }; 
 if(play&&!started)return <div className="modalwrap"><div className="modal"><div className="eyebrow">AbujaLifestyle beta</div><h2>Create your citizen</h2><p style={{color:'var(--muted)'}}>Choose a name and step into the city.</p><input className="field" placeholder="Username" value={name} onChange={e=>setName(e.target.value)}/><div className="choice">{['🧑🏾','👩🏾','🧔🏾','👩🏿','🧑🏿','🧔🏿'].map(x=><button className={avatar===x?'active':''} onClick={()=>setAvatar(x)} key={x}>{x}</button>)}</div><div className="actions"><button className="btn" onClick={()=>setPlay(false)}>Cancel</button><button className="btn primary" onClick={enterCity}>Enter Abuja →</button></div></div></div>;
 return <div className="shell"><nav className="nav"><div className="logo">ABUJA<span>LIFE</span></div><div className="navlinks"><span>Explore</span><span>How it works</span><span>Businesses</span><span>About</span></div><button className="btn primary" onClick={()=>setPlay(true)}>Play now</button></nav>{!started?<><section className="hero"><div><div className="eyebrow">A living city, online</div><h1>Live your<br/>Abuja story.</h1><p>Build a life in a virtual Abuja. Find a home, get a job, meet people, explore the city and make your own story.</p><div className="actions"><button className="btn primary" onClick={()=>setPlay(true)}>Create your citizen →</button><button className="btn">Explore the city</button></div></div><div className="city-preview"><span className="pin p1">Wuse</span><span className="pin p2">Maitama</span><span className="pin p3">Jabi</span><span className="pin p4">Garki</span><div className="preview-card"><strong>🌆 Abuja is alive</strong><small>Join citizens exploring the city right now.</small></div></div></section><section className="stats"><div className="stat"><b>6</b><span>districts in V1</span></div><div className="stat"><b>24/7</b><span>persistent city</span></div><div className="stat"><b>∞</b><span>stories to create</span></div></section></>:<section className="game"><div className="gamehead"><div><div className="eyebrow">Citizen mode</div><h2>Welcome, {name} {avatar}</h2><div style={{color:'var(--muted)'}}>You are in {zone}. Explore Abuja and meet other citizens.</div></div><button className="btn" onClick={()=>setStarted(false)}>Exit city</button></div><div className="gamegrid"><div className="map"><div className="road"></div><div className="road r2"></div>{zones.map(([n,c,d])=><button key={n} className={'zone '+c} onClick={()=>setZone(n)}><b>{n}</b><small>{d}</small></button>)}<i className="player u1"></i><i className="player u2"></i><i className="player u3"></i></div><aside className="side"><div className="profile"><small>Wallet</small><div className="money">₦{wallet.toLocaleString()}</div><small>🏠 Starter apartment · 💼 {job || 'Looking for work'}</small></div><h3>Online citizens</h3><div className="players">{online.map(p=><div className="online" key={p}><span><i className="dot"></i>{p}</span><small>online</small></div>)}</div><div className="actions"><button className="btn primary" style={{width:'100%'}} onClick={findJob}>{job?'Change job':'Find a job'}</button><button className="btn" style={{width:'100%'}}>Open chat</button></div></aside></div></section>}</div>
}
